### PR TITLE
Bump

### PR DESCRIPTION
**Pull request by kornelski**
How about making a release?

### CODE REVIEW

**Comment by softprops** [comment]
Good idea. I'll start drafting some changelog notes from the commits since 0.6.0 https://github.com/softprops/hyperlocal/compare/0.6.0...master

**Comment by kornelski** [comment]
I've updated the changelog

**Comment by kornelski** [comment]
ping @softprops

**Comment by kornelski** [comment]
@softprops Can you make a release?

**Comment by softprops** [comment]
@kornelski all set just published 0.7.0 with your changes. Thanks!

**Pull request merged**
