### PR TITLE
port hyperlocal client to latest hyper

### PR DESCRIPTION
**Pull request by danieleades**
This was required to support porting shiplift to futures 0.3 (https://github.com/softprops/shiplift/pull/191).

I've disabled the server implementation for now, and have ported only the client.

### CODE REVIEW

**Comment by softprops** [comment]
@danieleades I just merged https://github.com/softprops/hyperlocal/pull/25 let me know if that unblocks what you were blocked on for this pull

**Comment by danieleades** [comment]
DON'T MERGE THIS YET!

but it is ready for review. the only thing that will change is a dependency version.

tokio has just released a stable release using futures::Stream, instead of futures-preview::Stream. I would expect Hyper to bump it's dependency any day now. Once that happens, this pull request should be updated.

only then will i be unblocked downstream (otherwise we have a mixture of `futures-preview::Stream` and `futures::Stream` in the dependencies, and they don't play nicely together).

**Comment by danieleades** [comment]
i'm happy this is ready to merge. it's a major change, and a big refactor of the client and uri modules.

I would squash merge this, the commit history is a little messy...

**Comment by danieleades** [comment]
For visibility, hyper has just merged the move to futures, rather than futures-preview. Once this is released, hyperlocal should bump the hyper dependency and move to stable tokio

**Comment by danieleades** [comment]
hyper has just released. will update this pull request in the next couple of days.

**Comment by danieleades** [comment]
this is now updated to latest hyper.

**Comment by danieleades** [comment]
closes #23

**Comment by danieleades** [comment]
closes #22

**Comment by danieleades** [comment]
ping @softprops

**Comment by softprops** [comment]
Sorry for the many delays on this. @danieleades I'll try to commit to going though this but the end of the weekend.

**Comment by softprops** [comment]
This looks great! I'm shoot for a release this weekend

**Pull request merged**
